{
	"version": 1767770560,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/backgroundday-sheet0.png",
		"images/base-sheet0.png",
		"images/yellowbirdmidflap-sheet0.png",
		"images/yellowbirdmidflap-sheet1.png",
		"images/scorechecker-sheet0.png",
		"images/tint-sheet0.png",
		"images/play-sheet0.png",
		"images/gameover-sheet0.png",
		"images/restart-sheet0.png",
		"images/pipe-sheet0.png",
		"media/hit.ogg",
		"media/die.ogg",
		"media/point.ogg",
		"media/wing.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}